apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Las etiquetas del servicio deben coincidir con las del deployment
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
