apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx  # Las etiquetas del deployment deben coincidir con el selector del servicio
  template:
    metadata:
      labels:
        app: nginx  # Las etiquetas del pod deben coincidir con el selector del servicio
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
